version: '2.0'
networks:
    my-network:
        external: true

services:
    api:
        container_name: flask_mqtt_service
        build: .
        networks:
            - my-network
        ports:
            - "9001:5000"
        environment:
            - DEVICE_NAME=kin123
    worker:
        container_name: flask_mqtt_worker
        build: 
            context: .
            dockerfile: Dockerfile.celery
        networks:
            - my-network
        environment:
            - CELERY_TYPE=worker
            - DEVICE_NAME=kin123
        
        ports:
            - "5000:5000"
    beat:
        container_name: flask_mqtt_beat
        build: 
            context: .
            dockerfile: Dockerfile.celeryBeat
        networks:
            - my-network
        environment:
            - CELERY_TYPE=beat
            - DEVICE_NAME=kin123
        
        ports:
            - "5001:5000"
    redis:
        image: redis:latest
        container_name: redis-mqtt
        networks:
            - my-network
        restart: on-failure
        ports:
            - "6379:6379"
